### ISSUE TITLE
Imports not working as expected

### ISSUE THREAD

**Issue by austinmeier** [Planteome/plant-stress-ontology#3]
The NCBI taxon classes are all in the imports ncbitaxon_terms.txt, but still show up on the upper level of the ontology after running make.

@marieALaporte

**Comment by marieALaporte** [comment]
I guess that you are talking about the oops-edit.owl file. 
I think you need to manually add the imports. The ontology that you have in this file is not really the oops-edit.owl ontology (cf. the line 10). This is why the catalog file does not work.
