### ISSUE TITLE
Travis check broken?

### ISSUE THREAD

**Issue by austinmeier** [Planteome/plant-stress-ontology#8]
@marieALaporte @cmungall
my most recent update to oops-edit.owl has seemed to break the travis check.  I thought it is because I didn't update the imports in the Makefile, but even after adding the new 'aps-test-diseases.owl' and 'upper-level.owl' to the Makefile imports the travis check is still not working.

Cloning the repo, and opening the ontology on a different computer seemed to work okay, but I'd like that shiny green button to remind me that everything is okay.  

I'm guessing it has something to do with the paths of the imported ontologies?  If either of you could take a look at my last two commits, and see if they notice something odd, I'd be appreciative.

The error travis gave me:
make: **\* [mirror/ncbitaxon.owl] Error 137
The command "cd src/ontology && make test" exited with 2.

**Comment by cmungall** [comment]
Looks like travis timed out, ncbitaxon is huge

**Comment by cmungall** [comment]
If we know in advance all possible taxa, we could make a slim further upstream, but it's better to have thing just work, I'll look...

**Comment by marieALaporte** [comment]
@cmungall why is it important to have the all_imports running on Travis? I am probably missing something here. Travis checks is the ontology is consistent, right? Does the robot reason command use only the 'local' import folder? That would explain why those files needs to be generated by Travis. I hope I am clear.

**Comment by cmungall** [comment]
It's not really important, robot can use whatever is already checked in. Yes, this is more straightforward, let's just skip the make imports step when running make test

**Comment by marieALaporte** [comment]
@cmungall can you do the fix? I'm lost in my branches/conflicts...

**Comment by austinmeier** [comment]
I accepted Chris' merge, and the travis build still failed.  Seems odd that it would fail now.  I've had NCBITaxon in the imports for a while now.  Should  I just keep on moving along, and ignore the travis failure?

**Comment by marieALaporte** [comment]
replace 

> test: all 

by 

> test: $(ONT).owl $(ONT).obo

It should work

**Comment by austinmeier** [comment]
$$$  Thanks Marie!
